name: Test, Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare static files
        run: |
          mkdir -p public
          if [ -f index.html ]; then cp index.html public/; fi
          if [ -f style.css ]; then cp style.css public/; fi
          if [ -f app.js ]; then cp app.js public/; fi
          echo "Public contents:"
          ls -R public

      - name: Debug check before upload
        run: |
          echo "Current directory: $PWD"
          ls -R ./public

      - name: Upload a build artifact
        uses: actions/upload-artifact@v4
        with:
          name: art
          path: ./public
          retention-days: 7

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and run tests
        run: |
          npm install
          npm test

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test-code
    if: ${{success()}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/projet_statique:latest

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: test-code
    if: ${{ success() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Debug:list artifacts
        run: ls -R $GITHUB_WORKSPACE

  deploy-last-successful-version:
    runs-on: ubuntu-latest
    needs: test-code
    if: ${{ failure() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download last successful artifact
        uses: actions/download-artifact@v4
        with:
          name: art
          path: ./public

      - name: Deploy the last successful version to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
